use_frameworks!

target 'mLayout_Example' do
  pod 'mLayout', :path => '../'

  target 'mLayout_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
